/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.ejmcc.ui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.ejmcc.entidades.classes.Funcionario;
import net.ejmcc.entidades.enumeracoes.Sexo;
import net.ejmcc.entidades.enumeracoes.Situacao;
import net.ejmcc.persistencia.DAO.FuncionarioDAO;

/**
 *
 * @author Giu
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDadosFuncionario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Matricula = new javax.swing.JTextField();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Telefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Sexo = new javax.swing.JComboBox<>();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jButton_Salvar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jButton_Atualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Funcionario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefone");

        jTextField_Matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable_Tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Email", "Telefone", "Sexo", "Status"
            }
        ));
        jTable_Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Tabela);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        jComboBox_Sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));

        jComboBox_Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO", "LICENCAMEDICA" }));

        jButton_Salvar.setBackground(new java.awt.Color(102, 255, 102));
        jButton_Salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jButton_Excluir.setBackground(new java.awt.Color(255, 204, 204));
        jButton_Excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton_Atualizar.setBackground(new java.awt.Color(204, 204, 255));
        jButton_Atualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Atualizar.setText("Atualizar");
        jButton_Atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AtualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Telefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Matricula)
                                    .addComponent(jTextField_Nome)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Status, 0, 228, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton_Atualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(jButton_Excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jButton_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        // TODO add your handling code here:
        try{
            Funcionario objFuncionario = new Funcionario();
            objFuncionario.setMatricula(Integer.parseInt(jTextField_Matricula.getText()));
            //objFuncionario.setMatricula(jTextField_Matricula.getText());
            objFuncionario.setNome(jTextField_Nome.getText());
            objFuncionario.setEmail(jTextField_Email.getText());
            objFuncionario.setTelefone(jTextField_Telefone.getText());
            objFuncionario.setSexo(Sexo.valueOf(jComboBox_Sexo.getSelectedItem().toString()));
            objFuncionario.setStatus(Situacao.valueOf(jComboBox_Status.getSelectedItem().toString()));
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            objFuncionarioDAO.incluir(objFuncionario);
            this.limparTela();
            mostrarDadosFuncionario();
            JOptionPane.showMessageDialog(null,"Os dados foram Adicionados com sucesso");
                
    
        }catch (Exception erro){
           //JOptionPane.showMessageDialog(rootPane, erro.getMessage()); 
           JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Adicionar os dados");
        }
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        
            try{
                Funcionario objFuncionario = new Funcionario();
                FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
                if(jTable_Tabela.getSelectedRow() != -1){
                int row = jTable_Tabela.getSelectedRow();
                String valor = jTable_Tabela.getModel().getValueAt(row, 0).toString();
                if (row >= 0){
                if(jTable_Tabela.getSelectedRow() != -1){
                objFuncionarioDAO.excluir(Integer.parseInt(valor));
                DefaultTableModel model = (DefaultTableModel) jTable_Tabela.getModel();
                int SelectRowIndex = jTable_Tabela.getSelectedRow();
                model.removeRow(SelectRowIndex);
                this.limparTela();
                mostrarDadosFuncionario();
                JOptionPane.showMessageDialog(null,"Os dados foram Excluidos com sucesso");
                }else{
                   JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Excluir os dados"); 
                }}
                }else{
                JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Excluir os dados");
            }
                
            }catch (Exception erro){
               JOptionPane.showMessageDialog(rootPane, erro.getMessage()); 
            }
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_AtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AtualizarMouseClicked
        // TODO add your handling code here:
       try{
            Funcionario objFuncionario = new Funcionario();
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            if(jTable_Tabela.getSelectedRow() != -1){
                int i = jTable_Tabela.getSelectedRow();
                if(i>=0){
                    objFuncionario.setMatricula(Integer.parseInt(jTextField_Matricula.getText()));
                    objFuncionario.setNome(jTextField_Nome.getText());
                    objFuncionario.setEmail(jTextField_Email.getText());
                    objFuncionario.setTelefone(jTextField_Telefone.getText());
                    objFuncionario.setSexo(Sexo.valueOf(jComboBox_Sexo.getSelectedItem().toString()));
                    objFuncionario.setStatus(Situacao.valueOf(jComboBox_Status.getSelectedItem().toString()));
                    objFuncionarioDAO.atualizar(objFuncionario);
                    mostrarDadosFuncionario();
                    JOptionPane.showMessageDialog(null,"Os dados foram Atualizados com sucesso");
                }else{
                JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Atualizar os dados");
                }
            }else{
                JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Atualizar os dados");
            }
            
            /*DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();
            int i = jTable_Tabela.getSelectedRow();
            if(i>=0){
                modelo.setValueAt(jTextField_Matricula.getText(), i, 0);
                modelo.setValueAt(jTextField_Nome.getText(), i, 1);
                modelo.setValueAt(jTextField_Email.getText(), i, 2);
                modelo.setValueAt(jTextField_Telefone.getText(), i, 3);
                modelo.setValueAt(jComboBox_Sexo.getEditor().getItem(), i, 4);
                modelo.setValueAt(jComboBox_Status.getEditor().getItem(), i, 5);
                objFuncionarioDAO.atualizar(objFuncionario);
                mostrarDadosFuncionario();
                JOptionPane.showMessageDialog(null,"Atualizou");
            }
            else{
                JOptionPane.showMessageDialog(null,"Não Atualizou");
            }
            }//}*/
                
        
        }catch (Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            //JOptionPane.showMessageDialog(null,"ERRO - Não foi possivel Atualizar os dados");
        }
    
    }//GEN-LAST:event_jButton_AtualizarMouseClicked

    private void jTable_TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TabelaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable_Tabela.getModel();
        int i = jTable_Tabela.getSelectedRow();
        jTextField_Matricula.setBackground(Color.BLACK);
        jTextField_Matricula.setForeground(Color.WHITE);
        jTextField_Matricula.disable();
        jTextField_Matricula.setText(modelo.getValueAt(i, 0).toString());
        jTextField_Nome.setText(modelo.getValueAt(i, 1).toString());
        jTextField_Email.setText(modelo.getValueAt(i, 2).toString());
        jTextField_Telefone.setText(modelo.getValueAt(i, 3).toString());
        jComboBox_Sexo.setSelectedItem(jTable_Tabela.getModel().getValueAt(i, 4));
        jComboBox_Status.setSelectedItem(jTable_Tabela.getModel().getValueAt(i, 5));
        
    }//GEN-LAST:event_jTable_TabelaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
            jTable_Tabela.getSelectionModel().clearSelection();
            jTextField_Matricula.enable();
            jTextField_Matricula.setBackground(Color.WHITE);
            jTextField_Matricula.setForeground(Color.BLACK);
            limparTela();
    }//GEN-LAST:event_jPanel1MouseClicked
 
    
    private void limparTela(){
        jTextField_Matricula.setText("");
        jTextField_Nome.setText("");
        jTextField_Email.setText("");
        jTextField_Telefone.setText("");
    }
    
    private void mostrarDadosFuncionario(){
        try{
            FuncionarioDAO DadosFuncionarios = new FuncionarioDAO();
            ArrayList<Funcionario> lista = null;
            lista = DadosFuncionarios.listagem();
            if (lista.size()==0) return;
            DefaultTableModel model = (DefaultTableModel) jTable_Tabela.getModel();
            model.setNumRows(0);
            for(int pos=0; pos < lista.size(); pos++){
                String[] linha = new String[6];
                Funcionario aux = lista.get(pos);
                linha[0] = aux.getMatricula()+"";
                linha[1] = aux.getNome();
                linha[2] = aux.getEmail();
                linha[3] = aux.getTelefone();
                linha[4] = aux.getSexo().toString();
                linha[5] = aux.getStatus().toString();
                model.addRow(linha);
            }
        }catch (Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Atualizar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JComboBox<String> jComboBox_Sexo;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Tabela;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Matricula;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_Telefone;
    // End of variables declaration//GEN-END:variables
}
